### ISSUE TITLE
Explicitly load weights and add weights metadata

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/nsfw-server#6]
So we know what (version of) weights our data is made with.

Should be such that we can load them from IPFS.

**Comment by femans** [comment]
ok plan is: let docker pre-load the tensorflow model file and let node pull it in locally.

**Comment by dokterbob** [comment]
I would prefer including it in the repo, to be honest. It's only a couple of MB. I don't want to suddenly realise the model disappeared and it gives free versioning. Models live here: https://github.com/gantman/nsfw_model

Also happy with the models being on IPFS, as they are binary blobs anyways.
