### ISSUE TITLE
Allow concurrent requests

### ISSUE THREAD

**Issue by femans** [ipfs-search/nsfw-server#9]
From logs here below it seems that requests somehow are handled sequentially. 
Need to figure out if this is because of an operating system limitation, browser throttling or a server configuration, and fix it.

```
1640794675385 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/bafkreiazgl737iphtrr4777ju7o4chrniet7knzmtnydizhzbechwhnofi"} 415 (18366 ms)
1640794675517 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/QmbNA4nN3eLR12MBd6kVLkLiR82Pf69qZQGG4DdoM6siVq"} 200 (129 ms)
1640794675630 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/QmXnEU8ftNL4xxZeN1ksLNqVW9f7DHmeKZzEhYVKbmw76G"} 200 (111 ms)
1640794675792 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/QmSZzv7ux1LGwpehVcCMQ9ec945X6qE4qyjKDhCVwY25iw"} 200 (161 ms)
1640794675919 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/QmcPw2yPbtTiZQuabDnPgEHquURhwyDojomhSAc56y4DNM"} 200 (125 ms)
1640794678124 info 127.0.0.1 GET /classify {"url":"https://gateway.ipfs.io/ipfs/QmWx6ThfE8r6yYjAHSsc2xzJLS5nGdPyua6A75aRrLkP84"} 200 (18374 ms)
```

**Comment by femans** [comment]
Update: it seems there is a browser limitation i was previously unaware of: 
https://stackoverflow.com/questions/55830899/multiple-request-with-fetch-and-chrome-only-work-with-6-files-at-a-time-and-othe
https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html

This implies a workaround needs to be found for this.

**Comment by dokterbob** [comment]
On any modern browser, we're serving over HTTP/2, which uses multiplexing and allows for many, many, more simultaneous requests to be performed.
https://stackoverflow.com/questions/36835972/is-the-per-host-connection-limit-raised-with-http-2

**Comment by femans** [comment]
I be schooled. Of course, makes total sense. We may have to add some config to the hapi server.
